---
- name: run dns and subscription part
  hosts: internal
  become: true
  roles:
    - role: configure

- name: install postgres
  hosts: database_servers
  become: true
  collections:
    - community.postgresql
  tags:
    - database_servers
  roles:
    - role: postgres

- name: install flask
  hosts: app_servers
  become: true
  tags:
    - application_servers
  roles:
    - role: flask

- name: install haproxy
  hosts: load_balancers
  become: true
  tags:
    - load_balancers
  roles:
    - role: haproxy

