---

- name: Add IPv4 DNS server addresses
  nmcli:
    conn_name: "System eth0"
    type: ethernet
    dns4:
      - "{{ dnserver.0 }}"
      - "{{ dnserver.1 }}"
      - "{{ dnserver.2 }}"
    state: present
  register: network_really

- name: change peerdns in ifcfg file
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "{{ item }}"
    state: present
  loop:
    - PEERDNS=no # needed to survive reboots
  register: network_really # register if something changed

- name: if network changed restart network
  service:
    name: NetworkManager
    state: restarted
  when: network_really.changed

# now the redhat subscription
- name: install katello package
  yum:
    name: "{{ satellite_katello_cert }}"
    state: present
    disable_gpg_check: true

- name: register the system
  redhat_subscription:
    state: present
    activationkey: "{{ activationkey }}"
    org_id: "{{ activationorg }}" 
    auto_attach: true

- name: install firewall
  dnf:
    name: firewalld
    state: latest

#    - name: start firewalld
#      service:
#        name: firewalld
#        enabled: yes
#        state: started
